backend:
  name: git-gateway
  branch: master
media_folder: 'images/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/pages/blogs'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: Title, name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
